name: CI

on:
  pull_request:
    branches: "*"
  push:
    branches: master

jobs:
  test:
    strategy:
      fail-fast: false

    runs-on: ubuntu-latest

    steps:
      - name: Install Crystal
        uses: oprypin/install-crystal@v1

      - name: Donwload sources
        uses: actions/checkout@v2

      - name: Check formatting
        run: crystal tool format --check

      - name: Install dependencies
        run: shards install

      - name: Run linter
        run: ./bin/ameba

      - name: Run migrations
        run: crystal sam.cr db:create @ db:migrate

      - name: Run specs
        run: crystal spec --error-trace
